### ISSUE TITLE
MIUI14.0.29无法使用

### ISSUE THREAD

**Issue by usherzhao** [GSWXXN/UnlockMIUICameraSnap#2]
更新到MIUI14.0.29后在设置里找不到街拍功能开关了，希望大佬可以修复一下

**Comment by usherzhao** [comment]
**----part 1 start----
[ 2023-06-14T21:25:06.200     1000:  2545:  2545 I/LSPosed-Bridge  ] Loading module com.tsng.hidemyapplist from /data/app/~~5jSqmAHWaPzg36stYoRuyg==/com.tsng.hidemyapplist-Sys6IGre3__ZgB0c6dUd0g==/base.apk
[ 2023-06-14T21:25:06.213     1000:  2545:  2545 I/LSPosed-Bridge  ]   Loading class icu.nullptr.hidemyapplist.xposed.XposedEntry
[ 2023-06-14T21:25:06.229     1000:  2545:  2545 I/LSPosed-Bridge  ] Loading module com.variable.apkhook from /data/app/~~RtB37S1sJSIzwOS25il_NA==/com.variable.apkhook--zLXWOumUIbyYZQ3jUa4hA==/base.apk
[ 2023-06-14T21:25:06.240     1000:  2545:  2545 I/LSPosed-Bridge  ]   Loading class com.variable.apkhook.Hook.MainHook
[ 2023-06-14T21:25:06.583     1000:  2545:  2545 I/LSPosed-Bridge  ] [ INFO] 06-14 21:25:06 (HMA-XposedEntry) Hook entry
[ 2023-06-14T21:25:11.558     1000:  2545:  2545 I/LSPosed-Bridge  ] [DEBUG] 06-14 21:25:11 (HMA-XposedEntry) Got pms: com.android.server.pm.PackageManagerService$IPackageManagerImpl@4c19778
[ 2023-06-14T21:25:11.562     1000:  2545:  2545 I/LSPosed-Bridge  ] [ INFO] 06-14 21:25:11 (HMA-Bridge) Initialize HMAService - Version 95
[ 2023-06-14T21:25:11.566     1000:  2545:  2545 I/LSPosed-Bridge  ] [ INFO] 06-14 21:25:11 (HMA-Service) Data dir: /data/system/hide_my_applist_xggxmrtpyhtdtyvx
[ 2023-06-14T21:25:11.591     1000:  2545:  2545 I/LSPosed-Bridge  ] [ INFO] 06-14 21:25:11 (HMA-Service) Config loaded
[ 2023-06-14T21:25:11.593     1000:  2545:  2545 I/LSPosed-Bridge  ] [ INFO] 06-14 21:25:11 (PmsHookTarget33) Load hook
[ 2023-06-14T21:25:11.758     1000:  2545:  2545 I/LSPosed-Bridge  ] [ INFO] 06-14 21:25:11 (ZygoteArgsHook) Load hook
[ 2023-06-14T21:25:11.759     1000:  2545:  2545 I/LSPosed-Bridge  ] [ INFO] 06-14 21:25:11 (ZygoteArgsHook) App data isolation enabled: true
[ 2023-06-14T21:25:11.759     1000:  2545:  2545 I/LSPosed-Bridge  ] [ INFO] 06-14 21:25:11 (ZygoteArgsHook) Vold app data isolation enabled: true
[ 2023-06-14T21:25:11.759     1000:  2545:  2545 I/LSPosed-Bridge  ] [ INFO] 06-14 21:25:11 (HMA-Service) Hooks installed
[ 2023-06-14T21:25:11.760     1000:  2545:  2545 I/LSPosed-Bridge  ] [ INFO] 06-14 21:25:11 (HMA-Service) HMA service initialized
[ 2023-06-14T21:25:11.796     1000:  2545:  2545 I/LSPosed-Bridge  ] [ INFO] 06-14 21:25:11 (HMA-Bridge) Initialize service proxy
[ 2023-06-14T21:25:11.797     1000:  2545:  2545 I/LSPosed-Bridge  ] [ INFO] 06-14 21:25:11 (HMA-XposedEntry) Bridge service injected
[ 2023-06-14T21:25:14.643     1002:  5646:  5646 I/LSPosed-Bridge  ] Loading module com.ztc1997.mockbluetoothdevice from /data/app/~~ErkeL83j5OE9CtOpyXC4Gg==/com.ztc1997.mockbluetoothdevice-GO3KTmsDJQ3xPJv-migWmA==/base.apk
[ 2023-06-14T21:25:14.652     1002:  5646:  5646 I/LSPosed-Bridge  ]   Loading class com.ztc1997.mockbluetoothdevice.Hook
[ 2023-06-14T21:25:14.655     1002:  5646:  5646 I/LSPosed-Bridge  ] Loading module net.ankio.bluetooth from /data/app/~~DcksMqKcCEpSrXBiNEbC9Q==/net.ankio.bluetooth-fWfVJXCuc626kHuKM15wpg==/base.apk
[ 2023-06-14T21:25:14.695     1002:  5646:  5646 I/LSPosed-Bridge  ]   Loading class net.ankio.bluetooth.hook.Main
[ 2023-06-14T21:25:14.697     1002:  5646:  5646 I/LSPosed-Bridge  ]   Loading class net.ankio.bluetooth.hook.MainServer
[ 2023-06-14T21:25:14.788     1002:  5646:  5646 I/LSPosed-Bridge  ] AnkioのBluetooth : lpparam.packageName
[ 2023-06-14T21:25:14.788     1002:  5646:  5646 I/LSPosed-Bridge  ] AnkioのBluetooth : 蓝牙模拟启动
[ 2023-06-14T21:25:14.788     1002:  5646:  5646 I/LSPosed-Bridge  ] AnkioのBluetooth : 关闭蓝牙模拟功能
[ 2023-06-14T21:25:14.958     1000:  5863:  5863 I/LSPosed-Bridge  ] Loading module com.qingyu.mi5g from /data/app/~~JUOtSusMtEt-JZQdKj98tQ==/com.qingyu.mi5g-P_VtqjKf2Lnpe561zCq9og==/base.apk
[ 2023-06-14T21:25:14.961     1000:  5863:  5863 I/LSPosed-Bridge  ]   Loading class com.qingyu.mi5g.HookEntry_YukiHookXposedInit
[ 2023-06-14T21:25:29.650    10124:  9780:  9780 I/LSPosed-Bridge  ] Loading module com.gswxxn.camerasnap from /data/app/~~8HNGOexSopD79RaUQ9Yn2w==/com.gswxxn.camerasnap-vEAtxpvvOX-p5fmv9cfDSA==/base.apk
[ 2023-06-14T21:25:29.655    10124:  9780:  9780 I/LSPosed-Bridge  ]   Loading class com.gswxxn.camerasnap.hook.HookEntry_YukiHookXposedInit
[ 2023-06-14T21:25:31.287    10124:  9780:  9780 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][E][com.android.camera]--> An exception occurred in the Hooking Process of YukiHookAPI
[ 2023-06-14T21:25:31.287    10124:  9780:  9780 E/LSPosed-Bridge  ] java.lang.IllegalArgumentException: uniqueFindMethodInvoking() Error: invokingList must contain exactly one item; Data: {}
	at a.k.e(Unknown Source:359)
	at b.a.f(Unknown Source:59)
	at a.m.c(Unknown Source:153)
	at a.o.a(Unknown Source:418)
	at com.gswxxn.camerasnap.hook.HookEntry_YukiHookXposedInit.handleLoadPackage(Unknown Source:14)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1398)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3100)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3092)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6948)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
[ 2023-06-14T21:25:32.078    10124:  9780:  9780 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][E][com.android.camera]--> An exception occurred in the Hooking Process of YukiHookAPI
[ 2023-06-14T21:25:32.078    10124:  9780:  9780 E/LSPosed-Bridge  ] java.lang.IllegalArgumentException: uniqueFindMethodInvoking() Error: invokingList must contain exactly one item; Data: {}
	at a.k.e(Unknown Source:359)
	at b.a.f(Unknown Source:59)
	at a.m.c(Unknown Source:153)
	at a.o.a(Unknown Source:418)
	at com.gswxxn.camerasnap.hook.HookEntry_YukiHookXposedInit.handleInitPackageResources(Unknown Source:14)
	at de.robv.android.xposed.IXposedHookInitPackageResources$Wrapper.handleInitPackageResources(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_InitPackageResources.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at de.robv.android.xposed.XposedInit.cloneToXResources(Unknown Source:67)
	at de.robv.android.xposed.XposedInit.b(Unknown Source:0)
	at de.robv.android.xposed.XposedInit$2.afterHookedMethod(Unknown Source:34)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.createResources(Unknown Source:17)
	at android.app.ResourcesManager.getResources(ResourcesManager.java:1161)
	at android.app.LoadedApk.getResources(LoadedApk.java:1395)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3100)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3092)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6948)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
[ 2023-06-14T21:25:34.511    10290: 11006: 11006 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~U0qwb_VEOjGgNrrrL7yHoQ==/com.fkzhang.wechatxposed-H7dkvV764vieIHoyfhqhEw==/base.apk
[ 2023-06-14T21:25:34.522    10290: 11006: 11006 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-06-14T21:25:35.942    10290: 11006: 11006 I/LSPosed-Bridge  ] WeXposed: com.tencent.mm loading com.fkzhang.wechatxposed
[ 2023-06-14T21:25:36.351    10290: 11006: 11006 I/LSPosed-Bridge  ] WeXposed: wxcore (160) loaded successfully!
[ 2023-06-14T21:25:36.371    10290: 11006: 11006 I/LSPosed-Bridge  ] WeXposed: com.fkzhang.wechatxposed [WechatXposed](2.39|104): wechat version 8.0.37(2380)
[ 2023-06-14T21:25:36.371    10290: 11006: 11006 I/LSPosed-Bridge  ] WeXposed: com.fkzhang.wechatxposed load time: 441
[ 2023-06-14T21:25:38.420    10290: 11006: 11245 I/LSPosed-Bridge  ] WeXposed: 微X模块 2.39_4.32 (9,160) p
[ 2023-06-14T21:25:38.491    10290: 11006: 11245 I/LSPosed-Bridge  ] WeXposed: Wechat: 8.0.37_2380 {64,arm64} (0x28002537)[48d5fde2]
[ 2023-06-14T21:25:38.724    10290: 11006: 11217 I/LSPosed-Bridge  ] WeXposed: feature loaded: base 422
[ 2023-06-14T21:25:39.055    10290: 11006: 11217 I/LSPosed-Bridge  ] WeXposed: feature loaded: donation 27
[ 2023-06-14T21:25:39.822    10290: 11816: 11816 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~U0qwb_VEOjGgNrrrL7yHoQ==/com.fkzhang.wechatxposed-H7dkvV764vieIHoyfhqhEw==/base.apk
[ 2023-06-14T21:25:39.843    10290: 11827: 11827 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~U0qwb_VEOjGgNrrrL7yHoQ==/com.fkzhang.wechatxposed-H7dkvV764vieIHoyfhqhEw==/base.apk
[ 2023-06-14T21:25:39.854    10290: 11807: 11807 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~U0qwb_VEOjGgNrrrL7yHoQ==/com.fkzhang.wechatxposed-H7dkvV764vieIHoyfhqhEw==/base.apk
[ 2023-06-14T21:25:39.934    10290: 11816: 11816 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-06-14T21:25:40.040    10290: 11807: 11807 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-06-14T21:25:40.049    10290: 11827: 11827 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
-----part 1 end----
**

**Comment by GSWXXN** [comment]
相机的版本是多少呢

**Comment by usherzhao** [comment]
5.0.000710.6

**Comment by GSWXXN** [comment]
5.0.x 的相机使用了新的混淆策略, 我已经完成大部分的方法反混淆, 但是似乎这个版本的相机重构了设置界面, 所以设置项依然不能正常显示. 目前我正在向下适配 4.3.x 的相机, 之后我会想办法继续适配 5.0.x. 到时候如果你有时间的话, 可以请你帮忙测试吗

**Comment by usherzhao** [comment]
我可以配合测试,没问题,或者能否把设置功能放在插件的配置界面呢?这样是不是就不需要在相机的设置界面显示?

**Comment by GSWXXN** [comment]
可以考虑这个解决方案 :-)

**Comment by GSWXXN** [comment]
d366f2d 68c41fa
